name: python3

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python3
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -e robotics
        pip install -e quadruped\arachnid
    - name: Test Robotics
      working-directory: robotics
      run: |
        coverage run -m pytest robotics\test
        coverage xml
    - name: Test Arachnid
      working-directory: quadruped\arachnid
      run: |
        coverage run -m pytest quadruped\arachnid\test
        coverage xml
    - name: CodeCov
      uses: codecov/codecov-action@v2.1.0
      with:
        file: ./**/*.xml